name: Deploy to EC2
on:
push:
branches:
- main
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v3
- name: Copy files to EC2
run: |
ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@<204.236.202.80>
"mkdir -p /home/ec2-user/app"
scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./*
ec2-user@<204.236.202.80>:/home/ec2-user/app
- name: Deploy application
run: |
ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@<204.236.202.80>
